### PR TITLE
multi-server support with HashClient

### PR DESCRIPTION
**Pull request by skywaymsn**
Allows users to take advantage of the multi-server support built in to PyMemcache

### CODE REVIEW

**Comment by methane** [comment]
Which version of pymemcache has HashClient?

In setup.py:

```
    install_requires=["Flask", "pymemcache>=1.2.3", "six"],
```

**Comment by skywaymsn** [comment]
It appeared in 1.3.0, but does not look like it was useful until 1.3.4 (current is 1.3.8)

**Comment by methane** [comment]
OK, please update setup.py to "pymemcache>=1.3.4".

**Comment by methane** [comment]
thanks

**Comment by skywaymsn** [comment]
Thank you!!!

**Pull request merged**
